# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v3.6.0
      with:
        files: '**/*.java'
        files-excluded: 'app/src/main/java/org/sepp/Config.java'
      
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      #   # Set to true to not commit the changes
      #   skipCommit: # optional, default is false
      #   # Version of Google Java Format to use
      #   version: # optional
      #   # Recommended on MacOS machines
      #   githubToken: # optional
      #   # Commit message
      #   commitMessage: # optional, default is Google Java Format
          

    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: app/build/reports/tests/test/
    
    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

  # dependency-submission:

    # runs-on: ubuntu-latest
    # permissions:
      # contents: write

    # steps:
    # - uses: actions/checkout@v4
    # - name: Set up JDK 21
      # uses: actions/setup-java@v4
      # with:
        # java-version: '21'
        # distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    # - name: Generate and submit dependency graph
      # uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
